#!/bin/sh

jarpath=wookieerunner.jar
framework=../../android/aosp/out/host/linux-x86/framework:$PWD
exec java -Xmx128M -Djava.ext.dirs="$framework" -Dcom.android.wookieerunner.bindir="$progdir" -jar "$jarpath" "$@"
