#!/bin/bash

absolute_dir="$( cd "$( dirname "$0" )" && pwd )"

export LD_LIBRARY_PATH="/usr/local/lib/"
export LD_RUN_PATH="/usr/local/lib/"
aster_jarpath="$absolute_dir/jar/aster.jar"
jar_files="${absolute_dir}/jar"

debug_parameters=""

if [ z"$1" == z"-debug" ]; then
    debug_parameters='-Xdebug -Xrunjdwp:transport=dt_socket,address=5487,server=y,suspend=n'
    shift
    echo ""
    echo "Run in debug mode.....use jdb by typing...."
    echo "$ jdb -attach 127.0.0.1:5487"
fi

exec java $debug_parameters -Xms512M -Xmx512M -Djava.ext.dirs="${jar_files}" -jar "${aster_jarpath}" "$@"
